### ISSUE TITLE
Tourism Detail: After clicking on a recipe the detail view opens, but there is no way to get back to the overview inside

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-tourism-detail#17]
This behavior is actually OK if we have only a single ID, but not good if we have more, because we cannot switch back to the other entries in the list.

It seems that it is only happening when the content-id list is empty.

**Comment by maximiliannocker** [comment]
![image](https://user-images.githubusercontent.com/61493299/121350842-6af2b600-c92b-11eb-8654-691c61983806.png)
We have on top at the left side a back button. Currently there was another bug with loading the content, maybe it had to do with this? Or was this back button not present?

**Comment by Piiit** [comment]
@maximiliannocker Strange I got a mail with a comment but it is no longer here, have you deleted it?

**Comment by maximiliannocker** [comment]
@Piiit Yes I deleted the comment one minute later. It is everything clear and I fixed the bug

**Comment by Piiit** [comment]
@maximiliannocker @sseppi 

We have the component online at https://webcomponents.opendatahub.testingmachine.eu/webcomponent/e6c628d4-810b-489d-b8ec-1b33c8f025c6... please test
