### ISSUE TITLE
As a Web component Store manager I want to have the Detail Web Component online

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-tourism-detail#2]
Konverto is working on these web components.

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/e6c628d4-810b-489d-b8ec-1b33c8f025c6

Status: Konverto needs to fix a regression #17

**Comment by Piiit** [comment]
@sseppi Finally online at https://webcomponents.opendatahub.bz.it/webcomponent/e6c628d4-810b-489d-b8ec-1b33c8f025c6
