### ISSUE TITLE
Final web-component integration should be possible with only one script tag

### ISSUE THREAD

**Issue by dulvui** [noi-techpark/webcomp-tourism-detail#4]
The final result should be that I can integrate the web-component in a site with only one script tag like:
`<script src="./webcomp-tourism-detail.js"></script>`

But at the moment two script tags are needed:
```
<script src="https://unpkg.com/vue"></script>
<script src="./webcomp-tourism-detail.js"></script>
```
@maximiliannocker

**Comment by Piiit** [comment]
Solved
